# These values are acquired from `ow-<hero>-color` in https://static.playoverwatch.com/blizzard-<hash>.css
# Found in every playoverwatch.com page.
heroes = {
    'ana': {'color': 0x9c978a, 'name': 'Ana'},
    'ashe': {'color': 0xb3a05f, 'name': 'Ashe'},
    'bastion': {'color': 0x24f9f8, 'name': 'Bastion'},
    'baptiste': {'color': 0x2892a8, 'name': 'Baptiste'},
    'brigitte': {'color': 0xefb016, 'name': 'Brigitte'},
    'doomfist': {'color': 0x762c21, 'name': 'Doomfist'},
    'dva': {'color': 0xee4bb5, 'name': 'D.Va'},
    'genji': {'color': 0xabe50b, 'name': 'Genji'},
    'hanzo': {'color': 0x837c46, 'name': 'Hanzo'},
    'junkrat': {'color': 0xfbd73a, 'name': 'Junkrat'},
    'lucio': {'color': 0xaaf531, 'name': 'Lúcio'},
    'mccree': {'color': 0xc23f46, 'name': 'McCree'},
    'mei': {'color': 0x87d7f6, 'name': 'Mei'},
    'mercy': {'color': 0xfcd849, 'name': 'Mercy'},
    'moira': {'color': 0x7112f4, 'name': 'Moira'},
    'orisa': {'color': 0xccb370, 'name': 'Orisa'},
    'pharah': {'color': 0x3461a4, 'name': 'Pharah'},
    'reaper': {'color': 0x333000, 'name': 'Reaper'},
    'reinhardt': {'color': 0xb9d5ad, 'name': 'Reinhardt'},
    'roadhog': {'color': 0x54515a, 'name': 'Roadhog'},
    'sigma': {'color': 0x3ba000, 'name': 'Sigma'},
    'soldier76': {'color': 0x525d9b, 'name': 'Soldier: 76'},
    'sombra': {'color': 0x9762ec, 'name': 'Sombra'},
    'symmetra': {'color': 0x3e90b5, 'name': 'Symmetra'},
    'torbjorn': {'color': 0xb04a33, 'name': 'Torbjörn'},
    'tracer': {'color': 0xffcf35, 'name': 'Tracer'},
    'widowmaker': {'color': 0xaf5e9e, 'name': 'Widowmaker'},
    'winston': {'color': 0x595959, 'name': 'Winston'},
    'wrecking_ball': {'color': 0x4a575f, 'name': 'Wrecking Ball'},
    'zarya': {'color': 0xff73c1, 'name': 'Zarya'},
    'zenyatta': {'color': 0xe1c931, 'name': 'Zenyatta'}
}
