digits = (
    '\N{DIGIT ZERO}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT ONE}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT TWO}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT THREE}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT FOUR}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT FIVE}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT SIX}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT SEVEN}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT EIGHT}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{DIGIT NINE}\N{COMBINING ENCLOSING KEYCAP}',
    '\N{KEYCAP TEN}')

clocks = (
    '\N{CLOCK FACE ONE OCLOCK}', '\N{CLOCK FACE ONE-THIRTY}',
    '\N{CLOCK FACE TWO OCLOCK}', '\N{CLOCK FACE TWO-THIRTY}',
    '\N{CLOCK FACE THREE OCLOCK}', '\N{CLOCK FACE THREE-THIRTY}',
    '\N{CLOCK FACE FOUR OCLOCK}', '\N{CLOCK FACE FOUR-THIRTY}',
    '\N{CLOCK FACE FIVE OCLOCK}', '\N{CLOCK FACE FIVE-THIRTY}',
    '\N{CLOCK FACE SIX OCLOCK}', '\N{CLOCK FACE SIX-THIRTY}',
    '\N{CLOCK FACE SEVEN OCLOCK}', '\N{CLOCK FACE SEVEN-THIRTY}',
    '\N{CLOCK FACE EIGHT OCLOCK}', '\N{CLOCK FACE EIGHT-THIRTY}',
    '\N{CLOCK FACE NINE OCLOCK}', '\N{CLOCK FACE NINE-THIRTY}',
    '\N{CLOCK FACE TEN OCLOCK}', '\N{CLOCK FACE TEN-THIRTY}',
    '\N{CLOCK FACE ELEVEN OCLOCK}', '\N{CLOCK FACE ELEVEN-THIRTY}',
    '\N{CLOCK FACE TWELVE OCLOCK}', '\N{CLOCK FACE TWELVE-THIRTY}')
